# Site Settings
baseurl: ""
url : "https://pebpung.github.io"

# Blog Settings
theme_settings :
  title : Flow
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/my.png
    username : Kimin Park
    description : 안녕하세요!
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills :
      - skill : Deeplearning & Vision
        value : 60  # Percent value

  # Icons
  icons :
    email: "mcuwwa29@google.com"
    linkedin:  # Full URL
    github: PEBpung
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : pebpung-github-io

# Pagination
paginate: 6
paginate_path: "blog/page:num"
google_fonts: NotoSansKR-Regular

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true

# Google plugin
plugins:
  google-analytics:
      tracking_id: UA-174230337-1
