# Site Settings
baseurl: ""
url: "https://pebpung.github.io"
future: true

# Blog Settings
theme_settings:
  title: ML감자
  favicon: assets/red.ico

  # Profile Settings
  profile:
    image: assets/img/profile/cafe.jpg
    username: pebpung
    description: Medical AI Research Engineer at Tesser
    experience:
      - start: 2021-12-17
        experience: Tesser, Medical AI Research
      - start: 2021-06-16
        end: 2021-12-16
        experience: Aiffel 강남 2기, 퍼실리테이터
      - start: 2020-07-23
        end: 2020-12-23
        experience: Aiffel 강남 1기, 영상처리 교육 이수

    skills:
      - skill: Pytorch
        value: 90 # Percent value
      - skill: Bentoml
        value: 70
      - skill: MLflow
        value: 60

  # Icons
  icons:
    email: "mcuwwa29@gmail.com"
    linkedin: https://www.linkedin.com/in/%EA%B8%B0%EB%AF%BC-%EB%B0%95-976b07197/
    github: PEBpung
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname: pebpung-github-io

# Pagination
paginate: 6
paginate_path: "blog/page:num"
google_fonts: Lato

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true

# Google plugin
plugins:
  google-analytics:
    tracking_id: UA-174230337-1

# Category
category_dir: category/
tag_dir: tag/

# Conversion
markdown: kramdown
lsi: false
excerpt_separator: "\n\n"
incremental: false
