# Site Settings
baseurl: ""
url : "https://pebpung.github.io"

# Blog Settings
theme_settings :
  title : ML감자
  favicon : assets/red.ico

  # Profile Settings
  profile :
    image : assets/img/myProfile.JPG
    username : pebpung
    description : 코딩과 개발을 좋아하고 AI Researcher를 꿈꾸고 있습니다.
    experience :
      - start : 2021-06-16
        end : 2021-12-16
        experience : Aiffel 강남 2기, 퍼실리테이터
      - start : 2020-07-23
        end : 2020-12-23
        experience : Aiffel 강남 1기, 영상처리 교육 이수
      
    skills :
      - skill : Pytorch
        value : 70  # Percent value
      - skill : Python 
        value : 60  
      - skill : Tensorflow
        value : 50  

  # Icons
  icons :
    email: "mcuwwa29@gmail.com"
    linkedin:  # Full URL
    github: PEBpung
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : pebpung-github-io

# Pagination
paginate: 6
paginate_path: "blog/page:num"
google_fonts: Lato

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true

# Google plugin
plugins:
  google-analytics:
      tracking_id: UA-174230337-1

# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Category
category_dir: category/
tag_dir: tag/


# -----------------------------------------------------------------------------
#  Advanced configuration
# -----------------------------------------------------------------------------
kramdown:
  footnote_backlink: '&#x21a9;&#xfe0e;'
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true