name: Deploy to GitHub Pages

on:
  push:
    branches: [astro]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "☁️ Checkout repository"
        uses: actions/checkout@v4

      - name: "📦 Install pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.1

      - name: "🔧 Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: "📦 Install dependencies"
        run: pnpm install

      - name: "🚀 Build the project"
        run: pnpm run build
        env:
          PUBLIC_GOOGLE_SITE_VERIFICATION: "jhz_ZekXaLWItUeQ0yjvYwGFHR9A9oD6lqOCbJVZhZ4"

      - name: "📤 Upload artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: "🌐 Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4
